#   Copyright 2026 Seweryn Dynerowicz
# 
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
# 
#          http://www.apache.org/licenses/LICENSE-2.0
# 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#          http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

import re
from enum import Enum
import networkx as nx
import matplotlib.pyplot as plt

from qelebrimbor.core.components import BgCube

import logging
console = logging.getLogger(__name__)

class SpacetimeTracingReport(Enum):
    FINAL = 0
    STEPS = 1

class SpacetimeTracer:
    def __init__(self, pruning: bool = False, reporting: SpacetimeTracingReport = SpacetimeTracingReport.FINAL):
        self.__nodes : dict[BgCube, int] = dict()
        self.__nodes_extended: set[BgCube] = set()
        self.__pruned = set() if pruning else None
        self.__trace: nx.Graph = nx.Graph()
        self.__reporting = reporting

    def add_node(self, vertex):
        current_id = len(self.__nodes)
        self.__nodes[vertex] = current_id
        self.__trace.add_node( current_id )

    def add_edge(self, source, target):
        self.__trace.add_edge(self.__nodes[source], self.__nodes[target])
        if self.__reporting == SpacetimeTracingReport.STEPS:
            layout = nx.drawing.layout.bfs_layout(self.__trace, start=0)
            nx.draw(self.__trace, layout, node_size=1)
            plt.show()

    def prune_node(self, vertex):
        if self.__pruned is not None:
            self.__pruned.add(vertex)

    # Because matplotlib doesn't like the coloring ANSI escape sequences.
    # Generated by Gemini (Google AI), May 2026
    __ANSI_ESCAPE = re.compile(r'\x1b\[[0-9;]*m')

    def report(self, cubes_to_label : list[BgCube] | None = None):
        labels = {}
        if cubes_to_label:
            for cube in cubes_to_label:
                labels[self.__nodes[cube]] = SpacetimeTracer.__ANSI_ESCAPE.sub('', str(cube))
        layout = nx.drawing.layout.bfs_layout(self.__trace, start = 0)

        points_discovered = len(self.__nodes)
        points_considered = sum(1 for vt in self.__trace.nodes if self.__trace.degree[vt] > 1)
        console.info(f"> Number of points considered : {points_considered}")
        console.info(f"> Number of points discovered : {points_discovered}")
        if self.__pruned is not None:
            console.info(f"> Number of pruning performed : {len(self.__pruned)}")

        nx.draw(self.__trace, layout, node_size = 1)
        nx.draw_networkx_labels(self.__trace, layout, labels)
        plt.show()
