#   Copyright 2026 Seweryn Dynerowicz
# 
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
# 
#          http://www.apache.org/licenses/LICENSE-2.0
# 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#          http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

import re
from enum import Enum
import networkx as nx
import matplotlib.pyplot as plt

import logging
console = logging.getLogger(__name__)

class SpacetimeTracingReport(Enum):
    FINAL = 0
    STEPS = 1

class SpacetimeTracer[Vertex]:
    def __init__(self, pruning: bool = False, reporting: SpacetimeTracingReport = SpacetimeTracingReport.FINAL):
        self.__trace: nx.Graph = nx.Graph()

        self.__points_discovered : dict[Vertex, int] = dict()
        self.__points_considered : set[Vertex] = set()
        self.__pruning_performed : set[Vertex] | None = set() if pruning else None

        self.__reporting = reporting
        self.__labels: dict[int, str] = dict()

    def add_node(self, vertex: Vertex, label: str | None = None):
        current_id = len(self.__points_discovered)
        self.__points_discovered[vertex] = current_id
        if label is not None:
            self.__labels[current_id] = SpacetimeTracer.__ANSI_ESCAPE.sub('', label)
        self.__trace.add_node( current_id )

    def add_edge(self, source, target):
        self.__trace.add_edge(self.__points_discovered[source], self.__points_discovered[target])
        if self.__reporting == SpacetimeTracingReport.STEPS:
            layout = nx.drawing.layout.bfs_layout(self.__trace, start=0)
            nx.draw(self.__trace, layout, node_size=1)
            plt.show()

    def prune_node(self, vertex):
        if self.__pruning_performed is not None:
            self.__pruning_performed.add(vertex)

    # Because matplotlib doesn't like the coloring ANSI escape sequences.
    # Generated by Gemini (Google AI), May 2026
    __ANSI_ESCAPE = re.compile(r'\x1b\[[0-9;]*m')

    def report(self):
        layout = nx.drawing.layout.bfs_layout(self.__trace, start = 0)
        nx.draw(self.__trace, layout, node_size = 1)
        nx.draw_networkx_labels(self.__trace, layout, self.__labels)
        plt.show()

        points_discovered = len(self.__points_discovered)
        points_considered = sum(1 for vt in self.__trace.nodes if self.__trace.degree[vt] > 1)
        console.info(f"> Number of points considered : {points_considered}")
        console.info(f"> Number of points discovered : {points_discovered}")
        if self.__pruning_performed is not None:
            console.info(f"> Number of pruning performed : {len(self.__pruning_performed)}")